version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
        dependency-file: requirements.dev.txt
      - python/install-deps:
        dependency-file: requirements.dev.txt
      - python/save-cache:
        dependency-file: requirements.dev.txt
      - run:
          command: tox
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
